// <auto-generated />
using System;
using Aklasa.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AKlasa.Migrations
{
    [DbContext(typeof(PilkaContext))]
    [Migration("20260602152451_DodanoDateMeczu")]
    partial class DodanoDateMeczu
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("Aklasa.Models.Druzyna", b =>
                {
                    b.Property<int>("IdDruzyny")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BilansBramkowy")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BramkiStracone")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BramkiZdobyte")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IloscMeczy")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IloscPorazek")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IloscRemisow")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IloscZwyciestw")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NazwaKlubu")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Punkty")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdDruzyny");

                    b.ToTable("Druzyna");
                });

            modelBuilder.Entity("Aklasa.Models.Mecz", b =>
                {
                    b.Property<int>("IdMeczu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BramkiGosci")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BramkiGospodarzy")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataMeczu")
                        .HasColumnType("TEXT");

                    b.Property<int?>("GoscId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("GospodarzId")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdMeczu");

                    b.HasIndex("GoscId");

                    b.HasIndex("GospodarzId");

                    b.ToTable("Mecz");
                });

            modelBuilder.Entity("Aklasa.Models.Transfer", b =>
                {
                    b.Property<int>("IdTransferu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataTransferu")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DruzynaDoId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DruzynaOdId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ZawodnikId")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdTransferu");

                    b.HasIndex("DruzynaDoId");

                    b.HasIndex("DruzynaOdId");

                    b.HasIndex("ZawodnikId");

                    b.ToTable("Transfer");
                });

            modelBuilder.Entity("Aklasa.Models.Zawodnik", b =>
                {
                    b.Property<int>("IdZawodnika")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DruzynaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IloscAsyst")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IloscBramek")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Imie")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nazwisko")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IdZawodnika");

                    b.HasIndex("DruzynaId");

                    b.ToTable("Zawodnik");
                });

            modelBuilder.Entity("Aklasa.Models.Mecz", b =>
                {
                    b.HasOne("Aklasa.Models.Druzyna", "Gosc")
                        .WithMany()
                        .HasForeignKey("GoscId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Aklasa.Models.Druzyna", "Gospodarz")
                        .WithMany()
                        .HasForeignKey("GospodarzId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Gosc");

                    b.Navigation("Gospodarz");
                });

            modelBuilder.Entity("Aklasa.Models.Transfer", b =>
                {
                    b.HasOne("Aklasa.Models.Druzyna", "DruzynaDo")
                        .WithMany()
                        .HasForeignKey("DruzynaDoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Aklasa.Models.Druzyna", "DruzynaOd")
                        .WithMany()
                        .HasForeignKey("DruzynaOdId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Aklasa.Models.Zawodnik", "Zawodnik")
                        .WithMany()
                        .HasForeignKey("ZawodnikId");

                    b.Navigation("DruzynaDo");

                    b.Navigation("DruzynaOd");

                    b.Navigation("Zawodnik");
                });

            modelBuilder.Entity("Aklasa.Models.Zawodnik", b =>
                {
                    b.HasOne("Aklasa.Models.Druzyna", "Druzyna")
                        .WithMany("Zawodnicy")
                        .HasForeignKey("DruzynaId");

                    b.Navigation("Druzyna");
                });

            modelBuilder.Entity("Aklasa.Models.Druzyna", b =>
                {
                    b.Navigation("Zawodnicy");
                });
#pragma warning restore 612, 618
        }
    }
}
